.TH vtclock 1 vtclock\-VERSION
.SH NAME
vtclock \- virtual terminal clock
.SH SYNOPSIS
.B vtclock
.RB [ \-bg
.IR color]
.RB [ \-fg
.IR color]
.BR vtclock " ..."
.SH DESCRIPTION
.B vtclock
is a toy clock for terminal.
.SH OPTIONS
.TP
.B \-bg NUMBER
defines background color
.TP
.B \-fg NUMBER
defines foreground color
.SH COLORS NUMBERS
0 default
.br
1 black
.br
2 red
.br
3 green
.br
4 yellow
.br
5 blue
.br
6 magenta
.br
7 cyan
.br
8 white
.br
